### ISSUE TITLE
Nether roof is still at y=127

### ISSUE THREAD

**Issue by muzikbike** [SoapyXM/WorldHeightBooster#5]
Overworld generation was changed to make use of the doubled height, so why not the Nether?
![2020-11-12_17 21 59](https://user-images.githubusercontent.com/52297970/98973832-29706880-250c-11eb-9aa0-ed2c32ed21bd.png)

Either raise it to 255 (so there's still an empty half for building in) or 511 (to maximise the amount of actual Nether)

**Comment by SoapyXM** [comment]
This is not a bug.
